# Generated by Django 2.2.11 on 2020-03-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=30, null=True, verbose_name='昵称')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('login_time', models.CharField(default='', max_length=12, verbose_name='最近一次登陆时间')),
                ('avatar', models.ImageField(null=True, upload_to='avatar/', verbose_name='头像')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
