# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avoid_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollowUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_records', to='user.User')),
                ('followed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_records', to='user.User')),
            ],
            options={
                'db_table': 'userfollowuser',
            },
        ),
    ]
