# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-26 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('introduce', models.CharField(max_length=50, verbose_name='文章简述')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞量')),
                ('watch_count', models.IntegerField(default=0, verbose_name='观看量')),
                ('collect_count', models.IntegerField(default=0, verbose_name='收藏量')),
                ('limit', models.CharField(choices=[('public', '公开'), ('private', '不公开')], default='public', max_length=20, verbose_name='权限')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='user.User')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='TopicCollectUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_id', to='topic.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_id', to='user.User')),
            ],
            options={
                'db_table': 'topiccollectuser',
            },
        ),
        migrations.CreateModel(
            name='TopicLikeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_id', to='topic.Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_id', to='user.User')),
            ],
            options={
                'db_table': 'topiclikeuser',
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='collect_users',
            field=models.ManyToManyField(related_name='collect_topics', through='topic.TopicCollectUser', to='user.User'),
        ),
        migrations.AddField(
            model_name='topic',
            name='like_users',
            field=models.ManyToManyField(related_name='like_topics', through='topic.TopicLikeUser', to='user.User'),
        ),
    ]
