# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-25 18:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicLikeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'topiclikeuser',
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, verbose_name='类型')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('introduce', models.CharField(max_length=50, verbose_name='文章简述')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞量')),
                ('watch_count', models.IntegerField(default=0, verbose_name='观看量')),
                ('collecton_count', models.IntegerField(default=0, verbose_name='收藏量')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='user.User')),
                ('like_user', models.ManyToManyField(related_name='like_user', through='topic.TopicLikeUser', to='user.User')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='TopicWatchUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_topic_id', to='topic.Topics')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_user_id', to='user.User')),
            ],
            options={
                'db_table': 'topicwatchuser',
            },
        ),
        migrations.AddField(
            model_name='topics',
            name='watch_user',
            field=models.ManyToManyField(related_name='watch_user', through='topic.TopicWatchUser', to='user.User'),
        ),
        migrations.AddField(
            model_name='topiclikeuser',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_topic_id', to='topic.Topics'),
        ),
        migrations.AddField(
            model_name='topiclikeuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user_id', to='user.User'),
        ),
    ]
