# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-25 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topiclikeuser',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topiclikeuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='topics',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='topicwatchuser',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topicwatchuser',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='topics',
            table='topic',
        ),
    ]
