# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-27 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='message_count',
            field=models.IntegerField(default=0, verbose_name='评论数量'),
        ),
    ]
