# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avoid_login'),
        ('topic', '0002_topic_message_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_image', models.ImageField(null=True, upload_to='topicimages/', verbose_name='文章图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_images', to='user.User')),
            ],
            options={
                'db_table': 'topicimages',
            },
        ),
    ]
