# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('except_finish_time', models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间')),
                ('level', models.CharField(choices=[('a', '一级'), ('b', '二级'), ('c', '三级'), ('d', '四级')], max_length=5, verbose_name='代办等级')),
                ('state', models.CharField(choices=[('todo', '代办'), ('completed', '完成')], default='todo', max_length=20, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daytodos', to='user.User')),
            ],
            options={
                'db_table': 'daytodo',
            },
        ),
        migrations.CreateModel(
            name='MonthTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(verbose_name='月')),
                ('level', models.CharField(choices=[('a', '一级'), ('b', '二级'), ('c', '三级'), ('d', '四级')], max_length=5, verbose_name='代办等级')),
                ('state', models.CharField(choices=[('todo', '代办'), ('completed', '完成')], default='todo', max_length=20, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthtodos', to='user.User')),
            ],
            options={
                'db_table': 'monthtodo',
            },
        ),
        migrations.CreateModel(
            name='WeekTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('year', models.IntegerField(verbose_name='年')),
                ('week', models.IntegerField(verbose_name='周')),
                ('level', models.CharField(choices=[('a', '一级'), ('b', '二级'), ('c', '三级'), ('d', '四级')], max_length=5, verbose_name='代办等级')),
                ('state', models.CharField(choices=[('todo', '代办'), ('completed', '完成')], default='todo', max_length=20, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weektodos', to='user.User')),
            ],
            options={
                'db_table': 'weektodo',
            },
        ),
        migrations.CreateModel(
            name='YearTodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=50, verbose_name='内容')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('year', models.IntegerField(verbose_name='年')),
                ('level', models.CharField(choices=[('a', '一级'), ('b', '二级'), ('c', '三级'), ('d', '四级')], max_length=5, verbose_name='代办等级')),
                ('state', models.CharField(choices=[('todo', '代办'), ('completed', '完成')], default='todo', max_length=20, verbose_name='状态')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yeartodos', to='user.User')),
            ],
            options={
                'db_table': 'yeartodo',
            },
        ),
    ]
