# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-28 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytodo',
            name='day',
            field=models.IntegerField(default=28, verbose_name='日'),
        ),
        migrations.AddField(
            model_name='daytodo',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='monthtodo',
            name='month',
            field=models.IntegerField(default=3, verbose_name='月'),
        ),
        migrations.AlterField(
            model_name='monthtodo',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='weektodo',
            name='week',
            field=models.IntegerField(default=5, verbose_name='周'),
        ),
        migrations.AlterField(
            model_name='weektodo',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='yeartodo',
            name='year',
            field=models.IntegerField(default=2020, verbose_name='年'),
        ),
    ]
