# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-29 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200328_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytodo',
            name='day',
            field=models.IntegerField(default=89, verbose_name='日'),
        ),
    ]
