# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-04-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200410_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytodo',
            name='day',
            field=models.IntegerField(default=102, verbose_name='日'),
        ),
    ]
