# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-27 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='reply_count',
            field=models.IntegerField(default=0, verbose_name='回复数量'),
        ),
        migrations.AlterField(
            model_name='message',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_count',
            field=models.IntegerField(default=0, verbose_name='回复数量'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
    ]
