# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-27 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200327_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='parent_reply',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replys', to='message.Reply'),
        ),
    ]
